//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Class()
        {
            this.Reviews = new HashSet<Review>();
        }
    
        public int classID { get; set; }
        public string status { get; set; }
        public int corrections { get; set; }
        public System.DateTime classDate { get; set; }
        public System.DateTime createdAt { get; set; }
    
        public virtual Day Day { get; set; }
        public virtual LessonPlan LessonPlan { get; set; }
        public virtual Slot Slot { get; set; }
        public virtual Student Student { get; set; }
        public virtual StudentTutorRequest StudentTutorRequest { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Tutor Tutor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
