//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guardian
    {
        public Guardian()
        {
            this.Children = new HashSet<Child>();
        }
    
        public int guardianID { get; set; }
    
        public virtual ICollection<Child> Children { get; set; }
        public virtual User User { get; set; }
    }
}
