//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Juz
    {
        public int Juz_ID { get; set; }
        public string Arbabic_Start_Word { get; set; }
    
        public virtual Quran Quran { get; set; }
        public virtual surah surah { get; set; }
    }
}
