//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class LessonPlan
    {
        public LessonPlan()
        {
            this.Classes = new HashSet<Class>();
            this.Lessons = new HashSet<Lesson>();
        }
    
        public int lessonPlanID { get; set; }
        public string lessonName { get; set; }
    
        public virtual ICollection<Class> Classes { get; set; }
        public virtual ICollection<Lesson> Lessons { get; set; }
    }
}
