//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class onlineQuranTutorEntities3 : DbContext
    {
        public onlineQuranTutorEntities3()
            : base("name=onlineQuranTutorEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Certificate> Certificates { get; set; }
        public DbSet<Child> Children { get; set; }
        public DbSet<Class> Classes { get; set; }
        public DbSet<Day> Days { get; set; }
        public DbSet<Guardian> Guardians { get; set; }
        public DbSet<Juz> Juzs { get; set; }
        public DbSet<LessonPlan> LessonPlans { get; set; }
        public DbSet<Lesson> Lessons { get; set; }
        public DbSet<Quran> Qurans { get; set; }
        public DbSet<Review> Reviews { get; set; }
        public DbSet<Slot> Slots { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<StudentSlot> StudentSlots { get; set; }
        public DbSet<StudentTutorRequest> StudentTutorRequests { get; set; }
        public DbSet<Subject> Subjects { get; set; }
        public DbSet<surah> surahs { get; set; }
        public DbSet<Tutor> Tutors { get; set; }
        public DbSet<TutorSlot> TutorSlots { get; set; }
        public DbSet<TutorSubject> TutorSubjects { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
