//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slot
    {
        public Slot()
        {
            this.Classes = new HashSet<Class>();
            this.StudentSlots = new HashSet<StudentSlot>();
            this.TutorSlots = new HashSet<TutorSlot>();
        }
    
        public int slotID { get; set; }
        public System.TimeSpan startTime { get; set; }
        public System.TimeSpan endTime { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
    
        public virtual ICollection<Class> Classes { get; set; }
        public virtual ICollection<StudentSlot> StudentSlots { get; set; }
        public virtual ICollection<TutorSlot> TutorSlots { get; set; }
    }
}
