//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSlot
    {
        public int studentSlotID { get; set; }
    
        public virtual Day Day { get; set; }
        public virtual Slot Slot { get; set; }
        public virtual Student Student { get; set; }
    }
}
