//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.Classes = new HashSet<Class>();
            this.Students = new HashSet<Student>();
            this.StudentTutorRequests = new HashSet<StudentTutorRequest>();
            this.TutorSubjects = new HashSet<TutorSubject>();
        }
    
        public int subjectID { get; set; }
        public string subjectName { get; set; }
    
        public virtual ICollection<Class> Classes { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<StudentTutorRequest> StudentTutorRequests { get; set; }
        public virtual ICollection<TutorSubject> TutorSubjects { get; set; }
    }
}
