//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class surah
    {
        public surah()
        {
            this.Juzs = new HashSet<Juz>();
            this.Qurans = new HashSet<Quran>();
        }
    
        public int Id { get; set; }
        public string surah_names { get; set; }
        public string surah_Urdu_Names { get; set; }
    
        public virtual ICollection<Juz> Juzs { get; set; }
        public virtual ICollection<Quran> Qurans { get; set; }
    }
}
