//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TutorSubject
    {
        public int tutorSubjectID { get; set; }
    
        public virtual Subject Subject { get; set; }
        public virtual Tutor Tutor { get; set; }
    }
}
